#!/bin/sh
echo "Content-type: text/html"
echo ""

command="${QUERY_STRING%%=*}"
parameter="${QUERY_STRING#*=}"

# sanitize the input
command=${command//[^a-zA-Z0-9]/}
parameter=${parameter//[^a-zA-Z0-9\.]/}

if [ -z "$parameter" ] || [ "$parameter" = "$command" ]; then
  echo "unrecognized command"
  exit 0
else
  if [ "$command" = "ping" ]; then
    response=$(ping -c 1 -w 3 $parameter | grep time | sed -e 's/\.[[:digit:]]\+\ ms.*/ ms/')
    echo "$response"
  fi;

  if [ "$command" = "trace" ]; then
    result=$(traceroute -m 5 -q 1 -w 1 "$parameter")

    if [ $? -eq 1 ]; then
      result="Error with traceroute: Network is probably down"
    fi

    echo "<!DOCTYPE html>"
    echo "<html>"
    echo "<body>"
    echo "<pre style='color: white;' id='traceResponse'>$result</pre>"
    echo "</body></html>"
  fi;
fi
